// Archive/POCS/Poc-Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  imports: [FormsModule, HttpClientModule, CommonModule]
})
export class AppComponent {
  user: string = '';
  pass: string = '';
  text: string = '';
  boutonClass: string = 'login';

  constructor(private http: HttpClient) {}

  created() {
    const url = 'http://127.0.0.1:8080/login';
    const requestOptions = {
      username: this.user,
      password: this.pass
    };

    this.http.post(url, requestOptions).subscribe({
      next: (data) => {
        console.log(data);
        this.text = 'connected';
      },
      error: (error) => {
        console.error(error);
        this.text = 'failed to connect';
      }
    });
  }
}

<div>
  <input [(ngModel)]="user" placeholder="Username" />
  <input [(ngModel)]="pass" placeholder="Password" type="password" />
  <button [ngClass]="boutonClass" (click)="created()">Login</button>
  <p>Status = {{ text }}</p>
</div>

// Archive/POCS/Poc_Vue/src/App.vue
<script setup>
import { ref } from 'vue'

const text = ref('')
const user = ref('')
const pass = ref('')
const boutonClass = ref('login')

async function created(username, password) {
  const requestOptions = {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ username: username, password: password })
  };

  console.log(username.value)
  console.log(password.value)
  const url = "http://127.0.0.1:8080/login";
  console.log(url);

  try {
    const response = await fetch(url, requestOptions);
    console.log(response)
    if (!response.ok) throw new Error('Failed to login');

    const data = await response.json();
    console.log(data);
    text.value = 'connected';
  } catch (error) {
    console.error(error);
    text.value = 'failed to connect';
  }
}
</script>

<template>
  <input v-model="user" placeholder="Username">
  <input v-model="pass" placeholder="Password" type="password">
  <button :class="boutonClass" @click="created(user, pass)">Login</button>
  <p>Status = {{ text }}</p>
</template>

<style>
  .login {
    margin-left: 15px;
    padding: 15px;
    height: 40px;
    width: 80px;
  }
</style>
